pod 'AFNetworking', '~> 2.5.0'
pod 'SVProgressHUD', '~> 1.1.1'
pod 'UMengMessage', '~> 1.1.0.2'
pod 'UMengSocial', '~> 4.2.1'
pod 'UMengAnalytics', '~> 3.1.8'
pod 'UMengAnalytics-NO-IDFA', '~> 3.1.11'
pod 'SDWebImage', '~> 3.7.1'
pod 'JSONModel'
pod 'ELCImagePickerController', '~> 0.2.0'
pod 'TPKeyboardAvoiding', '~> 1.2.4'
pod 'RMPickerViewController', '~> 1.3.1'
pod 'RESideMenu', '~> 4.0.7' 
